#!/bin/bash

#ОПРЕДЕЛЯЕМ ОС
osfamily=$(cat /etc/issue.net | awk {'print $1'})
osver=$(cat /etc/issue.net | awk {'print $2'})

#РАЗРЯДНОСТЬ ОС
arc=`arch`
if [ "$arc" == "x86_64" ]; then arc=64 
else arc=32
fi

#ВЕРСИЯ ЯДРА LINUX
version_core=`uname -r | sed -e "s/-/ /" | awk {'print $1'}`

echo "┌──────────────────────────────────────────────────────────────┐"
echo "│                     Информация о системе                     │"
echo "└──────────────────────────────────────────────────────────────┘"
echo "                             ОС: $osfamily $osver"
echo "                 Разрядность ОС: $arch bit"
echo "              Версия ядра Linux: $version_core"
